/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *      
 */

                                                    
             
            
               
                           
                             
                       
                
                           
                                                             
                                             
                                                  
                                             
                                                                         
                                                    
                                             
                                                                     
                                                
                                                       

                                                             

                                    
                           
                       
                                        
     
  

                            
               
                                                
     
  

// A Fiber is work on a Component that needs to be done or was done. There can
// be more than one per component.
                      
                                                                             
                                                                               
                                                                         
                 

                                                                             
                                                                          
                                                                              
                                                                      

                                       
               

                                     
                     

                                                                            
                                  
                   

                                                             
            

                                                
                 

                       
                                                                         
                                                            

                                     

                                                                
                                                                            
                                                                        
                                                                        
                       

                                       
                      
                        
                

                                           
                                                                           
      
          
                                                              
                

                                                                        
                                                                                 
                                                             

                                            
                     

                                        
                     

                                                                  
                                    

                                                                             
                                                                              
                                                                  
                                                                             
                                                                                
                                         
                   

           
               
                      
                                 

                                                                      
                           

                                                                               
                                                                              
                
                            
                           

               
                    

                                                                            
                                                                               
                          
                          

                                                                                
                                                                      
                                                                                 
                                                                         
                          

                                                            
                                                 
                                                                         
                           

                                                            
                                                                        
                                                                         
                            

                                                         
                                                       
                                                                         
                            

                       
                                                                              
                                        
                 
                    
                               
                             
                                    
                               

                                                                            
                                           
   

                                 
                                                         
               

                                                                        
                     
                                     
                       
                                                                           
                 

                                                                              

                                                                       
                             
                                                                                
                                  
                                           
                                                           
                         
                                
                                                                    
                    

                                                                     
                                          
                                              
           

                                                                               
                                     
                  
                                 
                              
                                   

                      
                        
                     
                      
                          

                       

                        
                                
   

// The following attributes are only used by interaction tracing builds.
// They enable interactions to be associated with their async work,
// And expose interaction metadata to the React DevTools Profiler plugin.
// Note that these attributes are only defined when the enableSchedulerTracing flag is enabled.
                                          
                              
                                         
                                                             
   

                                          
                                                            
                                                           
     
  

// The follow fields are only used by enableSuspenseCallback for hydration.
                                                 
                                                        
   

// Exported FiberRoot type includes all properties,
// To avoid requiring potentially error-prone :any casts throughout the project.
// Profiling properties are only safe to access in profiling builds (when enableSchedulerTracing is true).
// The types are defined separately within this file to ensure they stay in sync.
// (We don't have to use an inline :any cast when enableSchedulerTracing is disabled.)
                         
                             
                                      
                                             
     
  

                                        
                             

                           
                 
                             
                                          
       
                                                                               
                      
                         
                  
                    
                      
                
                             
                                          
       
                                             
            
                                      
                                     
          
                  
                                      
                                     
          
                                                                   
                                                                       
                         
                                                                           
                    
                                     
          
                                                                      
                                   
                                                   
                                     
                                  
                                                              
                                                          
              
                             

                                     
   
